wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    project: "training"
    name: "show-o-training-stage2"
    output_dir: "show-o-training-stage2"
    max_train_examples_t2i: 40000000
    max_train_examples_mmu: 40000000
    save_every: 10000
    eval_every: 2500
    generate_every: 1000
    log_every: 50
    log_grad_norm_every: 500
    resume_from_checkpoint: 'latest'

model:
    vq_model:
        type: "magvitv2"
        vq_model_name: "showlab/magvitv2"

    showo:
        load_from_showo: False
        pretrained_model_path: "/home/azureuser/show-o-model"
        w_clip_vit: False
        vocab_size: 58498
        llm_vocab_size: 50295
        llm_model_path: 'microsoft/phi-1_5'
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 10  # <|soi|> <|eoi|> <|sov|> <|eov|> <|t2i|> <|mmu|> <|t2v|> <|v2v|> <|lvg|> <|pad|>

    gradient_checkpointing: True

dataset:
    gen_type: "t2i"
    und_type: "captioning"
    combined_loader_mode: "max_size_cycle"
    params:
        train_t2i_shards_path_or_url: []
        train_mmu_shards_path_or_url: 
            - 'https://biomedclip1234.blob.core.windows.net/data/train-{000000..000002}.tar?sp=r&st=2025-09-14T07:49:40Z&se=2025-09-29T16:04:40Z&spr=https&sv=2024-11-04&sr=c&sig=JG2ZxAyl4%2BVvA2mYgayRt0kewobyHweZQrAhhRHaWzA%3D'
        train_lm_shards_path_or_url: ""
        add_caption_prompt: True
        external_caption_path: ""
        external_journeydb_caption_path: ""
        external_laion12m_caption_path: ""
        external_cc12m_caption_path: ''
        validation_prompts_file: "validation_prompts/text2image_prompts.txt"
        shuffle_buffer_size: 1000
        num_workers: 32
        resolution: 256
        pin_memory: True
        persistent_workers: True

    preprocessing:
        max_seq_length: 128 # for text tokens
        resolution: 256
        center_crop: False
        random_flip: False

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-4
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 5000

training:
    gradient_accumulation_steps: 1
    noise_type: "mask"
    batch_size_t2i: 0
    batch_size_lm: 0
    batch_size_mmu: 10
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 10086
    max_train_steps: 1000000
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 0.0
    generation_timesteps: 12
    t2i_coeff: 0.0
    lm_coeff: 0.0
    mmu_coeff: 1.0
